<script>
$(document).ready(function()
{
    setInterval(loadTweets, 1000);
    
    $("a.stop").click(function(e)
    {
        e.preventDefault();
        $.ajax(
        {
            type: "GET",
            url: $(this).attr('href')
        }).done(function()
        {
            $("a.stop").removeClass('btn-danger');
            $("a.stop").addClass('btn-success');
            $("a.stop").text('Start Stream');
        });
        
    });
    
});

// Funtion to load tweets
loadTweets = function()
{
    var id = ($("ul#tweets li:first-child").attr('id') != undefined)?$("ul#tweets li:first-child").attr('id') : 0;
    
    $.ajax(
    {
        type: "GET",
        url: "/admin/index/feed/type/twitter/id/"+id,
        dataType: "json"

    }).done(function(data)
    {
        processTweets(data);
    });
}

// Function to handle feed error
error = function()
{
    alert("error");
}

// Function to process Tweets
processTweets = function(tweets)
{
    $.each(tweets, function(id, tweet)
    {
        $.Mustache.addFromDom();
        $.Mustache.render('tweet', tweet);
        $("#content ul#tweets").fadeIn('slow', function()
        {
            $("#content ul#tweets").mustache('tweet', tweet, {method: 'prepend'});
        });
    });
}

</script>
<script id="tweet" type="text/html">
    <li id="{{id}}" class="tweet">
        <div class="well clearfix">
            <div class="avatar pull-left">
                <img src="{{profile_img}}" alt="{{screen_name}}"/>
            </div>
            <div class="content pull-left">
                <h3>{{screen_name}} <small>{{name}}</small> <img src="/img/bird_16_gray.png" alt="twitter" /></h3>
                <p class="msg">{{content}}</p>
            </div>
        </div>
    </li>
</script>
<style>
    ul#tweets {list-style:none; padding:0; margin:0; height:450px; overflow: scroll;}
    li.tweet .avatar {margin-right:20px; padding:5px; border:2px solid #ccc;}
    p.msg {width:800px;}
</style>
<div id="content">
    <div class="page-header clearfix">
        <h1 class="pull-left">Tweets</h1>
        <p class="pull-right"><a class="btn btn-danger stop" href="<?=$this->baseUrl()?>/admin/index/stream/command/stop/id/1">Stop Stream</a></p>
    </div>
    <ul id="tweets">
        <?php
        foreach($this->tweets as $tweet)
        {
            ?>
            <li id="<?=$tweet->getId()?>" class="tweet">
                <div class="well clearfix">
                    <div class="avatar pull-left">
                        <img src="<?=$tweet->profileImg?>" alt="<?=$tweet->screenName?>"/>
                    </div>
                    <div class="content pull-left">
                        <h3><?=$tweet->screenName?> <small><?=$tweet->name?></small> <img src="/img/bird_16_gray.png" alt="twitter" /></h3>
                        <p class="msg"><?=$tweet->content?></p>
                    </div>
                </div>
            </li>
            <?php
        }
        ?>
    </ul>
</div>