<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120604232524 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE quote (id INT AUTO_INCREMENT NOT NULL, wording VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE streams (id INT AUTO_INCREMENT NOT NULL, tracker VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, running TINYINT(1) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE tweets (id INT AUTO_INCREMENT NOT NULL, stream_id INT DEFAULT NULL, twitter_id VARCHAR(255) NOT NULL, content VARCHAR(255) NOT NULL, source VARCHAR(255) NOT NULL, profile_img VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, created DATETIME NOT NULL, INDEX IDX_AA384025D0ED463E (stream_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE tweets ADD CONSTRAINT FK_AA384025D0ED463E FOREIGN KEY (stream_id) REFERENCES streams(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE tweets DROP FOREIGN KEY FK_AA384025D0ED463E");
        $this->addSql("DROP TABLE quote");
        $this->addSql("DROP TABLE streams");
        $this->addSql("DROP TABLE tweets");
    }
}
